#delimit cr
capture log close 
capture clear all 

global data_directory "C:\Users\Geoffrey Wodtke\Desktop\projects\nhood_schl_gaps\data\eclsk11\" 
global log_directory "C:\Users\Geoffrey Wodtke\Desktop\projects\nhood_schl_gaps\programs\_LOGS\" 

log using "${log_directory}08_create_v08_eclsk11_mi_final.log", replace 

/*******************************************************
PROGRAM NAME: 08_create_v08_eclsk11_mi_final.do
AUTHOR: KW/GW
PURPOSE: Re-label all variables and one-hot code catvars
********************************************************/

use "${data_directory}v07_eclsk11_mi.dta"

/**********************************
RE-LABEL VARIABLES AFTER IMPUTATION  
***********************************/
/*metadata*/
label variable childid "Child identification number" 
label variable parentid "Parent identification number" 
label variable schlid "Baseline school identification number"
label variable strat "W1 C1 Taylor Series Stratum" 
label variable psu "Primary sampling unit" 
label variable sampwt "Sampling weight" 
label variable minum "Imputation number" 

/*baseline controls*/
label variable gender "Child composite gender" 
label variable race "Child composite race" 
label variable brthwt "Child weight at birth - pounds" 
label variable marbrth "Mother married at time of childbirth"
label variable age1 "Child assessment age in months, Kindergarten Fall" 
label variable x1region "Census region, Kindergarten Fall"
label variable x1locale "Urban/rural location, Kindergarten Fall"
label variable lang1 "Home language English, Kindergarten Fall" 
label variable hhtot1 "Total number of people in household, Kindergarten Fall" 
label variable par1age1 "Parent 1 age in years, Kindergarten Fall" 
label variable par2age1 "Parent 2 age in years, Kindergarten Fall" 
label variable faminc2 "Family income in 2010, Kindergarten Spring" 
label variable pared2 "Parent highest education, Kindergarten Spring" 
label variable parocc1 "Highest parent average occupational prestige, Kindergarten Fall" 
label variable par1emp1 "Parent 1 employment status, Kindergarten Fall" 
label variable par2emp1 "Parent 2 employment status, Kindergarten Fall" 
label variable wichh1 "WIC benefits for child" 
label variable fstmp1 "Family received foodstamps in past 12 months, Kindergarten Fall" 
label variable tanf1 "Family received TANF ever, Kindergarten Fall" 
label variable married1 "Parent current marital status, Kindergarten Fall" 
label variable hhprnt1 "Both bio parents in home, Kindergarten Fall"
label variable pprctnm1 "Parent practices numbers with child, Kindergarten Fall" 
label variable preadbk1 "Parent reads books to child, Kindergarten Fall" 
label variable p1exp1 "Parental education expectations, Kindergarten Fall"
label variable extrn1 "Externalizing behavior scale, Kindergarten Fall"
label variable intrn1 "Internalizing behavior scale, Kindergarten Fall"
label variable mtvt1 "Child motivation scale, Kindergarten Fall"
label variable cooper1 "Child cooperitiveness scale, Kindergarten Fall"
label variable attn1 "Child attentiveness scale, Kindergarten Fall"
label variable hlthscale1 "Child health scale, Kindergarten Fall"
label variable nhpovrt1 "Neighborhood (census tract) poverty rate, Kindergarten Fall"
label variable nhlesshs1 "Neighborhood proportion less than HS, Kindergarten Fall" 
label variable nhcolgrd1 "Neighborhood proportion college graduate, Kindergarten Fall"
label variable nhfemhd1 "Neighborhood proportion female headed households, Kindergarten Fall" 
label variable nhunemprt1 "Neighborhood unemployment rate, Kindergarten Fall" 
label variable nhshrwht1 "Neighborhood proportion white, Kindergarten Fall"
label variable mththeta1 "Math test score theta, Kindergarten Fall" 
label variable rdtheta1 "Reading test score theta, Kindergarten Fall" 

/*outcomes*/
label variable rdtheta6 "Reading test score theta, 2nd grade Spring"
label variable rdtheta7 "Reading test score theta, 3rd grade" 
label variable rdtheta8 "Reading test score theta, 4th grade"
label variable rdtheta9 "Reading test score theta, 5th grade"
label variable mththeta6 "Math test score theta, 2nd grade Spring"
label variable mththeta7 "Math test score theta, 3rd grade" 
label variable mththeta8 "Math test score theta, 4th grade"
label variable mththeta9 "Math test score theta, 5th grade"

/*school characteristics*/
label variable mtvaladd "School value-added - 1st Grade Reading"
label variable rdvaladd "School value-added - 1st Grade Math"
label variable syrrnd4 "School goes year-round"
label variable stype4 "School is a public school, 1st grade Spring"
label variable slowgrd4 "School lowest grade level, 1st grade Spring"
label variable shighgrd4 "School highest grade level, 1st grade Spring"
label variable sfrlnch4 "% students eligible free or reduced lunch, 1st grade Spring" 
label variable shspnc4 "% students in school Hispanic/Latino, 1st grade Spring"
label variable sblk4 "% students in school Black/African American, 1st grade Spring"
label variable swht4 "% students in school White, 1st grade Spring"
label variable stotell4 "% students in school ELL, 1st grade Spring"
label variable sgif4 "% students in G/T program, 1st grade Spring"
label variable sspced4 "% students in special education, 1st grade Spring"
label variable ted4 "Teacher highest education, 1st grade Spring"
label variable tyrstch4 "Teacher years teaching, 1st grade Spring"
label variable tyrsch4 "Years teacher taught at this school, 1st grade Spring"
label variable tnexm4 "Teacher took and passed national board exam, 1st grade Spring"
label variable tcrt4 "Teacher has state certification, 1st grade Spring" 
label variable tgender4 "Teacher gender, 1st grade Spring" 
label variable trace4 "Teacher is white, 1st grade Spring" 
label variable pyrspr4 "Principal years as principal, 1st grade Spring"
label variable pyrstch4 "Principal years teaching, 1st grade Spring"
label variable ped4 "Principal has a doctorate, 1st grade Spring"
label variable pgender4 "Principal gender, 1st grade Spring" 
label variable prace4 "Principal is white, 1st grade Spring"
label variable sfnddc4 "School funding decreased from last year, 1st grade Spring"
label variable sstffinc4 "School staff salaries increased, 1st grade Spring"
label variable sstffdec4 "School salaries decreased, 1st grade Spring"
label variable sstfffrz4 "School staff salaries frozen, 1st grade Spring" 
label variable scafeok4 "School cafeteria meets needs, 1st grade Spring" 
label variable scompok4 "School computer lab meets needs, 1st grade Spring"
label variable slibok4 "School library meets needs, 1st grade Spring"
label variable sartok4 "School art room meets needs, 1st grade Spring" 
label variable sgymok4 "School gymnasium meets needs, 1st grade Spring" 
label variable smusok4 "School music room meets needs, 1st grade Spring"
label variable splayok4 "School playground meets needs, 1st grade Spring"
label variable sclssok4 "School classrooms meet needs, 1st grade Spring" 
label variable saudok4 "School auditorium meets needs, 1st grade Spring" 
label variable smultok4 "School multi-use room meets needs, 1st grade Spring"
label variable strg_pp_4 "Student-teacher ratio - regular classroom teachers per 100 students, 1st grade Spring"
label variable start_pp_4 "Student-teacher ratio - elective teachers per 100 students, 1st grade Spring"
label variable stgym_pp_4 "Student-teacher ratio - gym/health teachers per 100 students, 1st grade Spring" 
label variable stsp_pp_4 "Student-teacher ratio - special education teachers per 100 students, 1st grade Spring"
label variable stesl_pp_4 "Student-teacher ratio - ESL/bilingual teachers per 100 students, 1st grade Spring"
label variable stgft_pp_4 "Student-teacher ratio - G/T teachers per 100 students, 1st grade Spring" 
label variable stnrs_pp_4 "Studen-teacher ratio - school nurses per 100 students, 1st grade Spring" 
label variable stfpsy_pp_4 "Student-teacher ratio - school psychologists per 100 students, 1st grade Spring"
label variable stpar_pp_4 "Student-teacher ratio - para professionals per 100 students, 1st grade Spring" 
label variable stlib_pp_4 "Student-teacher ratio - librarians per 100 students, 1st grade Spring" 
label variable stcmp_pp_4 "Student-teacher ratio - computer teachers per 100 students, 1st grade Spring" 
label variable sttrn4 "Nonzero teacher turnover rate, 1st grade Spring" 
label variable sapri4 "Teacher feels school admin. sets priorities, 1st grade Spring"
label variable saenc4 "Teacher feels school admin. encourages staff, 1st grade Spring"
label variable sacns4 "Teacher feels school consensus expectations, 1st grade Spring"
label variable tenjy4 "Teacher enjoys job, 1st grade Spring"
label variable tmkdff4 "Teacher feels can make difference, 1st grade Spring"
label variable tchstch4 "Teacher would choose teaching again, 1st grade Spring"
label variable tacpt4 "Teacher is accepted at school, 1st grade Spring"
label variable tideas4 "Staff learn new ideas, 1st grade Spring"
label variable tppwrk4 "Teacher paperwork interferes with teaching, 1st grade Spring"
label variable tstfrec4 "Teacher feels staff recognized, 1st grade Spring"
label variable tlstd4 "Teacher thinks low academic standards, 1st grade Spring"
label variable tmssn4 "Faculty agree with school mission, 1st grade Spring" 
label variable sthft4 "How often theft problem at school, 1st grade Spring"
label variable scnfl4 "How often physical conflict problem at school, 1st grade Spring"
label variable sblly4 "How often bullying problem at school, 1st grade Spring"
label variable sdsrd4 "How often classroom disorder problem at school, 1st grade Spring"
label variable spsupp4 "Parents support school staff, 1st grade Spring"
label variable srptcrd4 "Frequency school sends report cards, 1st grade Spring"
label variable ststinf4 "Frequency school sends test info, 1st grade Spring"
label variable sptcnf4 "Frequency parent-teacher conferences, 1st grade Spring"
label variable strnsl4 "School has translators, 1st grade Spring"
label variable sprnpar4 "Hours per week principal meets parents, 1st grade Spring"
label variable sspprt4 "School has community support, 1st grade Spring"
label variable tord4 "How often per week teacher focuses on reading, 1st grade Spring"
label variable tomth4 "How often per week teacher focuses on math, 1st grade Spring" 
label variable ttrd4 "Teacher time spent per day on reading, 1st grade Spring"
label variable ttmth4 "Teacher time spent per day on math, 1st grade Spring"
label variable ttsgrp4 "Teacher time spent per day on small groups, 1st grade Spring"
label variable ttlgrp4 "Teacher time spent per day on large groups, 1st grade Spring"
label variable ttindv4 "Teacher time spent per day on individual activities, 1st grade Spring"
label variable ttpeer4 "Teacher time spent per day working with peers, 1st grade Spring"
label variable tevlclss4 "Importance teacher evaluate children relative to class, 1st grade Spring"
label variable tevlstd4 "Importance teacher evaluate children relative to standards, 1st grade Spring"
label variable tevlimp4 "Importance teacher evaluate children on improvement, 1st grade Spring" 
label variable tevleff4 "Importance teacher evaluate children on effort, 1st grade Spring"
label variable tevlpart4 "Importance teacher evaluate children on participation, 1st grade Spring"
label variable tevlbhv4 "Importance teacher evaluate children on behavior, 1st grade Spring"
label variable tevlcoop4 "Importance teacher evaluate children on cooperation, 1st grade Spring"
label variable tevldir4 "Importance teacher evaluate children on following directions, 1st grade Spring"
label variable tevltst4 "Frequency teacher evaluates children on standardized tests, 1st grade Spring"
label variable tevlqz4 "Frequency teacher evaluates children on class tests, 1st grade Spring" 
label variable tevlprj4 "Frequency teacher assigns projects, 1st grade Spring"
label variable tevlwrksh4 "Frequency teacher assigns worksheets, 1st grade Spring"
label variable tevlwrksa4 "Frequency teacher provides work samples, 1st grade Spring"
label variable tachrd4 "Times per week teacher uses achievement groups - reading, 1st grade Spring"
label variable tachmth4 "Teacher uses achievement groups - math, 1st grade Spring"
label variable thw4 "Times per week teacher assigns daily homework, 1st grade Spring"
label variable a4usebsl4 "How often teaches reading using basal series, 1st grade Spring"
label variable a4uselev4 "How often teaches reading using leveled reading bks, 1st grade Spring"
label variable a4usenew4 "How often teaches reading using news/magazines, 1st grade Spring"
label variable a4usekit4 "How often teaches reading using reading kits, 1st grade Spring"
label variable a4usecmp4 "How often teaches reading using computer software, 1st grade Spring"
label variable a4usetrd4 "How often teaches reading using trade books, 1st grade Spring" 
label variable a4useoth4 "How often teaches reading using other subject matters, 1st grade Spring"
label variable a4useman4 "How often teaches reading using manipulatives, 1st grade Spring" 
label variable a4usebgbk4 "How often teaches reading using big books, 1st grade Spring" 
label variable a4usedecb4 "How often teaches reading using decodable books, 1st grade Spring"
label variable a4useaubk4 "How often teaches reading using read-along/audio books, 1st grade Spring"
label variable a4useanth4 "How often teaches reading using anthology, 1st grade Spring"
label variable a4mainid4 "Since school start, frequency teacher taught main ideas in a story, 1st grade Spring" 
label variable a4retell4 "Since school start, frequency teacher taught retelling stories, 1st grade Spring" 
label variable a4deschar4 "Since school start, frequency teacher taught describing characters/events, 1st grade Spring"
label variable a4senses4 "Since school start, frequency teacher taught identify feelings/senses words, 1st grade Spring"
label variable a4whotell4 "Since school start, frequency teacher taught identify who is telling a story, 1st grade Spring"
label variable a4maintext4 "Since school start, frequency teacher taught identify main idea in inform text, 1st grade Spring"
label variable a4reassup4 "Since school start, frequency teacher taught identify reasons to support point, 1st grade Spring"
label variable a4simdiff4 "Since school start, frequency teacher taught describe sim/diff between two texts, 1st grade Spring"
label variable a4ficnonf4 "Since school start, frequency teacher taught recognizing fiction/non-fiction, 1st grade Spring" 
label variable a4cmpxinf4 "Since school start, frequency teacher taught reading informational text, 1st grade Spring" 
label variable a4cmpxpro4 "Since school start, frequency teacher taught reading prose/poetry, 1st grade Spring"
label variable a4segword4 "Since school start, frequency teacher taught segments words into phonemes, 1st grade Spring"
label variable a4manpho4 "Since school start, frequency teacher taught manipulating phonemes to form words, 1st grade Spring"
label variable a4sndwrd4 "Since school start, frequency teacher taught blending sounds to form words, 1st grade Spring"
label variable a4irregwd4 "Since school start, frequency teacher taught reading irregularly spelled words, 1st grade Spring"
label variable a4paceint4 "Since school start, frequency teacher taught reading pace/intonation/expression, 1st grade Spring"
label variable a4rdaccr4 "Since school start, frequency teacher taught reading accurately and fluently, 1st grade Spring" 
label variable a4useglos4 "Since school start, frequency teacher taught using glossaries and references, 1st grade Spring" 
label variable a4senctxt4 "Since school start, frequency teacher taught using sentence context gain meaning, 1st grade Spring"
label variable a4charplot4 "Since school start, frequency teacher taught identifying character, setting, plot, 1st grade Spring"
label variable a4gencsp4 "Since school start, frequency teacher taught generating questions about character/setting/plot, 1st grade Spring"
label variable a4predict4 "Since school start, frequency teacher taught predict what might occur, 1st grade Spring" 
label variable a4opinion4 "Since school start, frequency teacher taught writing opinion piece, 1st grade Spring" 
label variable a4infpiec4 "Since school start, frequency teacher taught writing informational piece, 1st grade Spring"
label variable a4narrtv4 "Since school start, frequency teacher taught writing narrative piece, 1st grade Spring"
label variable a4cnt20qty4 "Since school start, frequency teacher taught counting to 20 quantity, 1st grade Spring"
label variable a4relqty4 "Since school start, frequency teacher taught labeling relative quantity, 1st grade Spring"
label variable a4slvadsb4 "Since school start, frequency teacher taught solving word problems add/subtract, 1st grade Spring"
label variable a4slvadd34 "Since school start, frequency teacher taught solving word problem by add 3 num, 1st grade Spring"
label variable a4ctadsub4 "Since school start, frequency teacher taught relationship count/add/subtract, 1st grade Spring"
label variable a4eqlsign4 "Since school start, frequency teacher taught meaning of equal sign, 1st grade Spring" 
label variable a4sidequa4 "Since school start, frequency teacher taught both side of equation equal, 1st grade Spring"
label variable a4slvuknm4 "Since school start, frequency teacher taught solving for unknown number, 1st grade Spring"
label variable a4cnt1204 "Since school start, frequency teacher taught counting to 120, 1st grade Spring"
label variable a4nmrl1204 "Since school start, frequency teacher taught read/write numerals to 120, 1st grade Spring"
label variable a4numqty4 "Since school start, frequency teacher taught correspondence between num and qty, 1st grade Spring"
label variable a4tenones4 "Since school start, frequency teacher taught identifying 10s and 1s in 2-digit num, 1st grade Spring"
label variable a4relsym4 "Since school start, frequency teacher taught relative quantity using symbols, 1st grade Spring" 
label variable a4addto1004 "Since school start, frequency teacher taught adding nums sum to 100 or less, 1st grade Spring"
label variable a4find104 "Since school start, frequency teacher taught find 10 more or less without cnt, 1st grade Spring"
label variable a4skipcnt4 "Since school start, frequency teacher taught skip count by 5s, 10s, 100s, 1st grade Spring" 
label variable a4arr3obj4 "Since school start, frequency teacher taught arranging 3 objects by length, 1st grade Spring" 
label variable a4lng2by34 "Since school start, frequency teacher taught comparing length of 2 using 3rd obj, 1st grade Spring"
label variable a4lngmult4 "Since school start, frequency teacher taught measuring length by multiple copies, 1st grade Spring" 
label variable a4meatool4 "Since school start, frequency teacher taught measuring using tools, 1st grade Spring"  
label variable a4estlng4 "Since school start, frequency teacher taught estimating length in standard unit, 1st grade Spring" 
label variable a4telltime4 "Since school start, frequency teacher taught tell time in hours and 1/2 hours, 1st grade Spring" 
label variable a4wrttime4 "Since school start, frequency teacher taught write time in hours and 1/2 hours, 1st grade Spring" 
label variable a4slvcoin4 "Since school start, frequency teacher taught solving word prob with coins, 1st grade Spring" 
label variable a4drwgrph4 "Since school start, frequency teacher taught draw graph w/up to 4 categories, 1st grade Spring" 
label variable a4ansgrph4 "Since school start, frequency teacher taught answer Qs about data in graph, 1st grade Spring" 
label variable a4attrshp4 "Since school start, frequency teacher taught identifying attributes of shapes, 1st grade Spring" 
label variable a4dimcomp4 "Since school start, frequency teacher taught shapes together create composite shape, 1st grade Spring"
label variable a4parteql4 "Since school start, frequency teacher taught partitioning shapes in 2 & 4 shars, 1st grade Spring" 
label variable a4triquad4 "Since school start, frequency teacher taught triangle/quad/pent/hex/cubes, 1st grade Spring" 
label variable sattnd4 "School - % of daily attendance, 1st grade Spring" 
label variable tbhvr4 "Teacher rating of classroom behavior, 1st grade Spring"
label variable ccd_dstr_exppp4 "CCD data - total district expenditures per pupil, 1st grade Spring"

/*************
ONE-HOT CODING
**************/
tab race, gen(drace_)
tab x1locale, gen(dx1locale_)
tab x1region, gen(dx1region_)
tab par1emp1, gen(dpar1emp1_)
tab par2emp1, gen(dpar2emp1_) 

/********
SAVE DATA
*********/
saveold "${data_directory}v08_eclsk11_mi_final.dta", replace v(12)

log close 

clear

